#ifndef CODOGRAMIDS_H
#define CODOGRAMIDS_H

typedef enum {
  CODOGRAM_ID_MOUSE_MOVE,
  CODOGRAM_ID_SEND_KEY,
  CODOGRAM_ID_LEFT_MOUSE_CLICK,
  CODOGRAM_ID_MAX
} CodogramIds;

#endif // CODOGRAMIDS_H
